//import 'package:flutter//material.dart';
void main()
{
  String sehir = "ORDU";
  print("şehir :$sehir");
  String ulke = "TÜRKİYE";
  print(" ülke :$ulke");
  int telefon = 05393995115;
  print("telefon :$telefon");
  String email = "ismailcagan95@gmail.com";
  print("E-MAİL :$email");
  String meslek = "YAZILIM MÜHENDİSİ";
  print("meslek :$meslek");
  int stokMiktari = 52;
  print("stok miktarı :$stokMiktari");
  String musteriAdi = "İsmail";
  print("müşteri adı :$musteriAdi");
  int bakiye = 20000;
  print("bakiye :$bakiye");
  var dogumGunu = DateTime(1996,03,26);
  print(dogumGunu);
  int maas=20000;
  print("maas :$maas");
  bool medeniDurumBool = false;
  print("medeni durum bool :$medeniDurumBool");
  String medeniDurumString = "Bekar";
  print("medeni durum :$medeniDurumString");
  String urunYorum = "iyi";
  print("ürün yorum :$urunYorum");
  var odemeTarihi = DateTime(2022,12,06);
  print("ödeme tarihi :$odemeTarihi");
  int odeme = 1500;
  print("ödeme :$odeme");
  int siparisAdeti = 25;
  print("sipariş adeti :$siparisAdeti");
  String arabaModeli = "VOLVO";
  print("araba modeli :$arabaModeli");
  String kitapAdi = "metal fırtına";
  print("kitap adı :$kitapAdi");
  var yayinlamaTarihi = DateTime(2023,01,01);
  print("yayınlanma tarihi :$yayinlamaTarihi");
  int indirimMiktari = 250;
  print("indirim miktarı :$indirimMiktari");
  int odaSayisi = 3;
  print("oda sayısı :$odaSayisi");
  String enlem = "40° 49′ 59″ Kuzey";
  print("enlem :$enlem");
  String boylam = "37° 30′ 0″ Doğu ";
  print("boylam :$boylam");
  String urunAdi = "Bilgisayar";
  print("urun adı :$urunAdi");
  int yemekFiyati = 100;
  print("yemek fiyatı :$yemekFiyati");
  String marka = "MONSTER";
  print("marka :$marka");
  String muzikAdi = "mehter marşi";
  print("muzik adı :$muzikAdi");
  double videosuresi = 3.5;
  print("video süresi :$videosuresi");
  double urunPuani = 75.5;
  print("urun puanı :$urunPuani");
  String resimAdi = "görsel-1";
  print("resim adı :$resimAdi");
  const dosyaFormati = "text";
  print("dosya formatı :$dosyaFormati");
  String renk = "kırmızı";
  print("renk :$renk");
  //Color renkKodu = Color(255);
  //print("renk kodu :$renkKodu");
  String renkKodu = "#082567";
  print("renk kodu :$renkKodu");
  String telefonModeli = "vivo";
  print("telefon modeli :$telefonModeli");
  double ekranBoyutu =17.3;
  print("ekran boyutu :$ekranBoyutu");
  double agirlik = 95.3;
  print("ağırlık :$agirlik");
  String ulusalGun = "cuma";
  print("ulusal gün :$ulusalGun");
  String tatilGunu = "Cuma";
  print("tatil günü :$tatilGunu");
  var rezervasyonTarihi = DateTime(2023,01,01);
  print("rezervasyon tarihi :$rezervasyonTarihi");
  String sokakAdi = "asd sokak";
  print("sokak adı :$sokakAdi");
  String otobusHatti = "sşldfm";
  print("otobus hattı :$otobusHatti");
  double kalanDakika = 5.26;
  print("kalan dakika :$kalanDakika");
  var takipKodu = "adawpdlöaw";
  print("takip kodu :$takipKodu");
  var kuponKodu = "kdvmSLm";
  print("kupon kodu :$kuponKodu");
  String faturaAdresi = "lcsşlmefşcmlslşf";
  print("fatura adresi :$faturaAdresi");
}